Update github actions  workflow file

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -15,7 +15,7 @@ jobs:
       DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
       DD_ENV: ci
       DD_SERVICE: cypress-tests
-      DD_SITE: datadoghq.eu
+      DD_SITE: app.datadoghq.eu
       DD_CIVISIBILITY_AGENTLESS_ENABLED: "true"
       DD_LOGS_INJECTION: "true"
 
@@ -51,27 +51,40 @@ jobs:
             --browser chrome 2> time.log || true
 
       - name: Capture CPU/Memory metrics from time output
+        if: always()
+        shell: bash
         run: |
           echo "Extracting CPU and memory stats..."
-          CPU_TIME=$(grep "User time (seconds)" time.log | awk '{print $5}')
-          MAX_MEM=$(grep "Maximum resident set size" time.log | awk '{print $6}')
-          echo "CPU Time: $CPU_TIME"
-          echo "Max Memory: $MAX_MEM KB"
+          CPU_TIME=$(grep "User time (seconds)" time.log | awk '{print $5}' || echo "0")
+          MAX_MEM=$(grep "Maximum resident set size" time.log | awk '{print $6}' || echo "0")
 
+          echo "CPU Time: ${CPU_TIME:-0}"
+          echo "Max Memory: ${MAX_MEM:-0} KB"
+
+          CPU_TIME=${CPU_TIME:-0}
           MAX_MEM_MB=$((MAX_MEM / 1024))
 
-          datadog-ci metric send --apiKey ${DATADOG_API_KEY} --site ${DD_SITE} \
-            --type gauge \
-            --points "[[ $(date +%s), $CPU_TIME ]]" \
-            --metric "ci.cypress.cpu_time" \
-            --tags "env:ci,service:cypress-tests,step:run"
+          if [[ "$CPU_TIME" =~ ^[0-9]+([.][0-9]+)?$ ]]; then
+            echo "Sending CPU metric to Datadog..."
+            datadog-ci metric send --apiKey ${DATADOG_API_KEY} --site ${DD_SITE} \
+              --type gauge \
+              --points "[[ $(date +%s), $CPU_TIME ]]" \
+              --metric "ci.cypress.cpu_time" \
+              --tags "env:ci,service:cypress-tests,step:run"
+          else
+            echo "Skipping CPU metric: invalid value"
+          fi
 
-          datadog-ci metric send --apiKey ${DATADOG_API_KEY} --site ${DD_SITE} \
-            --type gauge \
-            --points "[[ $(date +%s), $MAX_MEM_MB ]]" \
-            --metric "ci.cypress.max_memory_mb" \
-            --tags "env:ci,service:cypress-tests,step:run"
-        shell: bash
+          if [[ "$MAX_MEM_MB" =~ ^[0-9]+$ ]]; then
+            echo "Sending Memory metric to Datadog..."
+            datadog-ci metric send --apiKey ${DATADOG_API_KEY} --site ${DD_SITE} \
+              --type gauge \
+              --points "[[ $(date +%s), $MAX_MEM_MB ]]" \
+              --metric "ci.cypress.max_memory_mb" \
+              --tags "env:ci,service:cypress-tests,step:run"
+          else
+            echo "Skipping Memory metric: invalid value"
+          fi
 
       - name: Upload JUnit test results to Datadog
         if: always()
